### ISSUE TITLE
Ability to not use Relay-GraphQL

### ISSUE THREAD

**Issue by gyzerok** [RisingStack/graffiti-mongoose#101]
Is there an ability to not expose Relay-GraphQL schema, but plain GraphQL? I know there were such ability in previous versions.

In this case you stick with the compatibility. It would be awesome to have plain GraphQL with an ability to switch to Relay compatible mode.

**Comment by tothandras** [comment]
@gyzerok Let me see what I can do. It will take some time, but you can always open a PR. :)

**Comment by d-winter** [comment]
Any new on this? Would also be interested in this feature

**Comment by pswoodworth** [comment]
@tothandras have you made any progress on this? If you'd be interested in sharing how you might go about it I might have time to take a crack at a PR.

**Comment by tothandras** [comment]
@pswoodworth sadly, no. Feel free to contact me if you need help for the PR ([andras.toth@risingstack.com](mailto:andras.toth@risingstack.com)).

**Comment by katopz** [comment]
I think I need this pretty soon How can I help? Did you guys have any approach yet?
I can see graph.cool call it [Simple  API](https://www.graph.cool/docs/reference/simple-api/pagination-ojie8dohju) vs [Relay API](https://www.graph.cool/docs/reference/relay-api/pagination-riekooth4o)

Maybe we can just rip out `input`, `viewer` and `edges`?
But I'm not sure about how can we toggle between `Simple  API` and `Relay API`

Any thought?
