### ISSUE TITLE
Confusing readme example

### ISSUE THREAD

**Issue by gyzerok** [RisingStack/graffiti-mongoose#11]
What does following code from readme example means? How can we return from a module?
```javascript
return yield graphql(schema, query);
```

**Comment by hekike** [comment]
@gyzerok hi, the example used `co` earlier and this allowed me to `yield` the promise.
I've changed the example now it uses Promise.
https://github.com/RisingStack/graffiti-mongoose/commit/0ec8290cb8ebee534c5754feedba42a7a2ba23e9

Does i help?

**Comment by gyzerok** [comment]
Thanks, now its clear to me
