### ISSUE TITLE
Mutation implementation

### ISSUE THREAD

**Issue by gyzerok** [RisingStack/graffiti-mongoose#12]
Is there any estimate time for mutation implementation?

**Comment by hekike** [comment]
@gyzerok we don't have detailed roadmap yet, but first we would like to finish the queries. Object type, field excluding etc. are still missing.

**Comment by gyzerok** [comment]
@hekike do you think so? I guess it would be nice to have both queries and mutations implemented in some way so everyone can start to use this tool, of course on hes own risk. Than you can implement it with maximum features.

**Comment by gyzerok** [comment]
Also I'm confused about version number. Why it 1.0 if you haven't finished core functionality?

**Comment by hekike** [comment]
@gyzerok yes it would be good to have mutations as soon as possible.
About version: we realised it with 1.0.0 and we are following http://semver.org

**Comment by hardchor** [comment]
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

:grin:

**Comment by tothandras** [comment]
Mutations are currently supported, most likely there will be changes in the payload formats.
