### ISSUE TITLE
validate on update

### ISSUE THREAD

**Issue by evollu** [RisingStack/graffiti-mongoose#121]
I may have missed something but I can't find a way to validate fields like email on update. Is there a way to do it?

**Comment by Secretmapper** [comment]
I think you should be able to hook it into the Mongoose Schema, though I'm not sure if it will be resolved into a proper graphql type.

**Comment by evollu** [comment]
@Secretmapper i think your propose for custom input type will definitely help me as I can create a custom graphql type. Are you planning to work on this?
I also tried mutation hooker but it is root level so I can't get what mutation is called

**Comment by Secretmapper** [comment]
@evollu I can't commit a date, but will probably implement it soon since I also need a custom enum type.

**Comment by evollu** [comment]
great let me know if I can help

**Comment by evollu** [comment]
I managed to find a way to do validation by adding root level hook
```
hooks: {
		mutation: {
			pre: (next, args, request, context) => {
				let invalid = validate(context.fieldName, args);
				if (invalid) {
					throw new Error(invalid);
				}
				next();
			}
		}
	}
```
but is there a way to respond with standard graphql errors? Is there a way to use graphql/errors in http://graphql.org/docs/api-reference-validation/?
