### ISSUE TITLE
Update data in field pre hook 

### ISSUE THREAD

**Issue by grimabe** [RisingStack/graffiti-mongoose#123]
In my user model I have a **password** field that I would like to hash when the user is created or updated.
I already achieve to do it with mongoose pre save hook. 

But it appears to be only working when creating the document because the **update mutation** doesn't seems to use the model save method.

So I thought about using the field pre hook like below but I don't know how to update the value.

````javascript
        password: {
            type: String,
            required: true,
            hooks: {
                pre: (next, root, args, request) => {
                    //replace  with hashed password
                    next();
                },
                post: (next) => next(`********`)
            }
        },
````

Is there a way to do that ?

Thank you

**Comment by tothandras** [comment]
Hi @grimabe,
you can change the arguments like:
```
pre: (next, root, args, ...rest) => {
   // replace  with hashed password
   args.password = hash(args.password)
   next(root, args, ...rest)
}
```
Give it a try and let me know if it worked or not!

**Comment by grimabe** [comment]
Hi @tothandras,
Thanks for the answer, I tried exactly the code you wrote but the field is still not modified in the database.

Do you have something else to try ?

**Comment by tothandras** [comment]
Hi @grimabe,
sorry for the delay. I've just realised that the field hooks are for query, not mutation. So this is what you need to do (using the [example](https://github.com/RisingStack/graffiti-mongoose/tree/master/example) in the project) to change arguments for mutations:
```javascript
const hooks = {
  mutation: {
    pre(next, args, context, info) {
      if (info.fieldName === 'updateUser') {
        args.name += ' MutationPreHook';
      }
      next(args, context, info);
    }
  }
};
const schema = getSchema([User], { hooks });
```

Let's see a user:
```
query {
  users {
    id,
    name
  }
}
```
![image](https://cloud.githubusercontent.com/assets/4157749/17148762/b47b4a32-5368-11e6-948b-778667f379c0.png)

Update its name:
```
mutation {
  updateUser(input: {id: "VXNlcjo1Nzk3YTA0NDdjZjhlMDQ4ODY5ZDRlNGQ=", name: "UserUpdated", clientMutationId: "0"}) {
    changedUser {
      id,
      name
    }
  }
}
```
![image](https://cloud.githubusercontent.com/assets/4157749/17148789/cc232a9c-5368-11e6-8225-0268738880b3.png)
