### ISSUE TITLE
Non-indexed fields as query parameters

### ISSUE THREAD

**Issue by d-winter** [RisingStack/graffiti-mongoose#124]
Hi.

Within the documentation you say:

_Supported query params: 
indexed fields_

When I run the example, I can also use non-indexed fields: 
`query foo {
  users(name:"User40") { 
  	name
  }
}`

Shouldn't this only be possible using the id and the indexed age field?
Thanks for your work so far!
Daniel

**Comment by tothandras** [comment]
Hi @d-winter,
you are right, I've changed that in the past. Should we restrict query for indexed fields only?

**Comment by d-winter** [comment]
Hey @tothandras ,
I thought this restriction was defined to avoid slow queries on non index fields.

**Comment by tothandras** [comment]
Hey @d-winter,
you are right, but we've removed this restriction. It's up to the developer to use index on a field, but we still allow it to be queried.
