### ISSUE TITLE
The 4th params of resolve hooks.pre middleware was always null

### ISSUE THREAD

**Issue by shenyzore** [RisingStack/graffiti-mongoose#127]
Is the home page's doc Resolve hooks section out of date or it's an issue?
In my test the 4th params of resolve hooks.pre middleware was always null, but the 5th params return right object contains `fieldName`.

**Comment by shenyzore** [comment]
ok, i think this is an issue in the `graffiti` lib.
It pass the same `request` object in `graphql` function at the 3rd and 4th parameters which are `rootValue` and `context`.
I use `express-graphql` lib instead of `graffiti` and it's work good.

**Comment by shenyzore** [comment]
Issue still, when i use `express-graphql` without provide the `context` parameter, graphql works well,but the 4th parameter of resolve hooks.pre middleware still null.
And when i provide the `context` parameter for graphql, the 4th parameter of resolve hooks.pre middleware contains it but graphql show errors "Cannot read property 'selectionSet' of undefined".

**Comment by tothandras** [comment]
Hi @shenyzore,
I [remember updating](https://github.com/RisingStack/graffiti/commit/4d20f70290601692b81930a3eabac378eb0ef89e) the parameters to graphql `>=5.0.0`, but I probably missed something. 
I see a lot of: `addHooks((rootValue, args, context, info) => {})` in `graffiti-mongoose` which seems to be still for the pre `5.0.0` version. 
Can you open a PR?

**Comment by tothandras** [comment]
Can you check with the latest graffiti and graffiti-mongoose?

**Comment by shenyzore** [comment]
I checked the latest graffiti and graffiti-mongoose and it works well, thanks!
