### ISSUE TITLE
Implicit dependency on babel-polyfill

### ISSUE THREAD

**Issue by yoadsn** [RisingStack/graffiti-mongoose#128]
Hey,
I believe a lib like graffiti-mongoose ought to not take implicit dependencies on the polyfills provided by Babel.
I currently have an issues when I update all my Babel tool chain grafitti-mongoose throws:

`ReferenceError: regeneratorRuntime is not defined`
In:
`\node_modules\@risingstack\graffiti-mongoose\lib\query\query.js:15`

When I restore the modules to the older version - it works.
Also, if I remove the `import 'babel-polyfill'` row from my entry point - the same error occurs even with the old modules.

So, like other libs, I think you should use the `transform-runtime` plugin and rely on `babel-runtime' as an explicit dependency.

I suspect more people who will use the latest version of Babel tools will start facing this problem (I will post more info when I pinpoint the exact cause).

I used both  `@risingstack/graffiti-mongoose@5.1.0` and `@risingstack/graffiti-mongoose@5.0.10` with the same results.
Thanks!

**Comment by yoadsn** [comment]
Additionally, if all that is required is the regenerator runtime - you can rely on `regenerator-runtime` explicitly.

**Comment by pbrain19** [comment]
did you ever get this to work? been trying for a whle now and no luck

**Comment by yoadsn** [comment]
Yeah, I got to the bottom of this.

I'm using Webpack - so I got it to work by including in Webpack a pre entry with `regenerator-runtime\runtime` which exported `regeneratorRuntime` globally before the babel loader (which uses the `transfrom-runtime` internally) had a chance to call it and prevent it from exporting later on when `babel-polyfill` was loaded.

So no my relevant part in webpack.config.js is:

```
...
entry: [
    'regenerator-runtime/runtime', // This is a workaround for grafitti's irresponsible dependency on Runtimeregenerator global availability. 
    './src/server.js'
  ],
...
```

:ghost:

**Comment by mo4islona** [comment]
+1

**Comment by tothandras** [comment]
Hi @yoadsn, @mo4islona, @pbrain19,
could you try out version `5.2.0`?
Thank you!

**Comment by yoadsn** [comment]
Sure, I'll upgrade and check it out - Problem is that usually when I upgrade Graffiti it breaks all kind of stuff and many dependencies have to be changed as well.
QA cycle is quite tedious - Here for example is a compatibility list I created when last updated:

Not Working:
@risingstack/graffiti@3.0.3
@risingstack/graffiti-mongoose@5.0.10
graphql@0.5.0

Not Working:
@risingstack/graffiti@3.0.4
@risingstack/graffiti-mongoose@5.0.10
graphql@0.5.0

Working:
@risingstack/graffiti@3.0.4
@risingstack/graffiti-mongoose@5.1.0
-> graphql-relay@0.4.2
graphql@0.5.0

Working:
@risingstack/graffiti@3.0.3
@risingstack/graffiti-mongoose@5.0.10
-> graphql-relay@0.3.6
graphql@0.4.18

**Comment by tothandras** [comment]
@yoadsn Sorry about that! We are not using GraphQL internally, so I just try out if the examples are working and that's all. I try my best to keep this project in a good shape despite this. :)
You can even try out other GraphQL middleware, like `express-graphql` with `graffiti-mongoose`.

**Comment by yoadsn** [comment]
@tothandras Thank you for the disclaimer.
Since I am basing a production app on this library today - would you advise against using the schema generation of `graffiti-mongoose` for production use?
The `graphql-js` and `graphql-relay` project evolve in a reasonable pace and with some breaking changes so I wonder if you will try and keep up or this repo is abandoned.

**Comment by tothandras** [comment]
@yoadsn It's perfectly fine if you are okay with the current feature set. You can always migrate to hand written schema later if you need more control over it. I try to keep up with dependency updates and fixing issues, but sadly, I can't focus on graffiti as I originally planned. And as always, PRs are always welcomed!
