### ISSUE TITLE
How to make a custom field: id?

### ISSUE THREAD

**Issue by Dugnist** [RisingStack/graffiti-mongoose#130]
As i understand - now my "id" generated from mongoose "_id" field, but how to make it custom?

**Comment by tothandras** [comment]
You need to create another field. `id` is used by Relay and it encodes the resource type along the mongoose `_id` too.

**Comment by Dugnist** [comment]
@tothandras ok, as then i can create unique field or rewrite _id during create new document?

**Comment by Dugnist** [comment]
@tothandras i try used "unique: true" in mongo schema and it did not work...(

**Comment by tothandras** [comment]
@Dugnist for what do you need a custom `id`?

**Comment by tothandras** [comment]
does this work or not?
```
new Schema({
    identifier: { type: String, index: { unique: true } }
})
```

**Comment by Dugnist** [comment]
@tothandras i need create a full object that include field "id" on the client-side and then push them on server...

**Comment by tothandras** [comment]
@Dugnist hmmm.. why not just use the ids you get back when inserting objects with a mutation? so you can have the ids on the client side too for new objects

**Comment by Dugnist** [comment]
@tothandras yes - index: { unique: true } is working. Thank you. And you really don't know maybe how can circumvent restriction with "id" field? The policy of my project require creating unique id on the client...(

**Comment by Dugnist** [comment]
@tothandras unfortunately i cannot do any request with my custom field "ID" without default field "id"...(

This mutation not working... I know why and it sadly...(

mutation{
  updateDocument(input:{
    name: "Name of Document",
    ID : "123",
    clientMutationId: "1"
  }) {
    changedDocument {
      ID
    }
  }
}

**Comment by tothandras** [comment]
@Dugnist To be honest I've never heard unique id and client side in the same sentence. :) As the user has full control over the sent object, you eventually need to validate it server side. 
What you can try is to use a plural query with the ID and then you can get the actual id to do the mutation.. it's something
