### ISSUE TITLE
Custom query thunk - accepts only InputObject types

### ISSUE THREAD

**Issue by yoadsn** [RisingStack/graffiti-mongoose#133]
## Overview of the Issue

The custom query function accepts the `types` object which only has the `InputObject` kind of the schema types.
This might make sense for the Custom Mutations but why is it so also for the queries?
Do I miss something?

## Suggest a Fix

Perhaps pass both kinds, the input and the normal types of the schema.

**Comment by tothandras** [comment]
Does this help #148?

**Comment by yoadsn** [comment]
Yeah, awesome.
I have implemented the same locally for testing..
When do you expect to deliver it?

**Comment by tothandras** [comment]
released in version `5.3.0` 😉
