### ISSUE TITLE
Fragments support

### ISSUE THREAD

**Issue by gyzerok** [RisingStack/graffiti-mongoose#15]
- [x] Inline fragments support
- [x] External fragments support

**Comment by gyzerok** [comment]
I'm going to investigate in external fragments support and come with PR.

**Comment by hekike** [comment]
Ok thanks!

**Comment by gyzerok** [comment]
Waiting answer on [the issue](https://github.com/RisingStack/graffiti-mongoose/issues/18) in GraphQL.js.

**Comment by hekike** [comment]
@gyzerok ok cool. I refactored the project structure, so please check it before start implementing something: https://github.com/RisingStack/graffiti-mongoose/tree/master/src

**Comment by gyzerok** [comment]
@hekike nice work! But I'm suggesting to use a little bit different file names. For example projection.js can be named getProjection.js. It's less confusing and this naming style is being used now in most repos as far as I know. Same with the schema.js - getSchema.js and etc.

**Comment by gyzerok** [comment]
Also I think it would be nice to split core and utilitary modules. Core modules in our case seems to be those which implements a graffiti adapter interface and are directly connected to scheme generation while ```getProjection``` is just an util. So I propose to create 2 dirs in ```src/```  (```core/``` and ```utils```) and split code between them. What do you think about this?

**Comment by gyzerok** [comment]
***P.S.:*** Or mb better names are ```adapter/``` and ```utils/```.

**Comment by hekike** [comment]
@gyzerok I agree that we should do some improvement here, but I'm not 100% sure what would be the best for now. Let's wait a little bit with this, until everything will be clear in my mind.

Btw it would be great to have a short Skype call about the future of `graffiti` if you are really interested in. What do you think?

**Comment by gyzerok** [comment]
@hekike Since I've started to play around GraphQL I thought about a tool to map existing MongoDB schema into GraphQL schema to avoid code duplication. How exited I was when found graffiti! So I'm very happy that I can help you somehow.

It mb be hard to speak to each other cuz of my poor verbal english skills. But we can try. Find me as ```gyzerok```.

**Comment by hekike** [comment]
@gyzerok I added fragment support and tests with a workaround: https://github.com/RisingStack/graffiti-mongoose/commit/25fc49cc8c709d1f7413f111560b61570f4504da

But we should fix this when `graphql-js` starts support getting the required fields.
Thanks to handling this!

**Comment by hekike** [comment]
@gyzerok they fixed it: https://github.com/graphql/graphql-js/issues/96 ;)

**Comment by gyzerok** [comment]
@hekike Yes, saw it todays morning :) Gonna come back with a solution in a few days if you not hurry.
