### ISSUE TITLE
Example project doesnt work with graffiti@3.1.1 and graffiti-mongoose@5.3.0

### ISSUE THREAD

**Issue by cellis** [RisingStack/graffiti-mongoose#150]
## Overview of the Issue

Example project doesn't work with @risingstack/graffiti-mongoose@5.3.0 and @risingstack/graffiti@3.1.1. (UNMET PEER DEPENDENCY: graphql )

## Reproduce the Error

Steps to reproduce:
1. `npm install --save @risingstack/graffiti-mongoose@5.3.0`
2. `npm install --save @risingstack/graffiti@3.1.1`
3. `npm install graphql`

Node version: `6.0.0`

## Suggested fix

The least common graphql is ^0.6.2, but graffit-mongoose@5.3.0 requires 0.7.0.
 
Perhaps update the example app to hardcode versions in a package.json of its own with:

```javascript
"dependencies": {
    "@risingstack/graffiti": "^3.1.1",
    "@risingstack/graffiti-mongoose": "^5.2.1",
    ...
}
```

**Comment by tothandras** [comment]
Thank you! I've updated the example dependencies.
