### ISSUE TITLE
Links to commits in changelog

### ISSUE THREAD

**Issue by gyzerok** [RisingStack/graffiti-mongoose#17]
I suggest to add links to commits in changelog.

**Comment by hekike** [comment]
Yes. I've seen this issue.
We are generating the `CHANGELOG.md` with the same tool ([conventional-changelog](https://www.npmjs.com/package/conventional-changelog)) as in the main `graffiti` project: https://github.com/RisingStack/graffiti/blob/master/CHANGELOG.md 

In `graffiti` it's working well. I don't know the reason yet.

**Comment by hekike** [comment]
I found the issue: git links were missing from the `package.json`

https://github.com/RisingStack/graffiti-mongoose/commit/2602415cc89f997f85f96b4d2241fc2ff55c6d07
