### ISSUE TITLE
How to mutate nested Schema?

### ISSUE THREAD

**Issue by danielmahon** [RisingStack/graffiti-mongoose#195]
## Overview of the Issue

I must be missing something but how do you create/update a nested schema? For example, I am unable to create the `street1` attribute under the `location` path. No errors are thrown.
## Reproduce the Error

![cursor_and_graphiql_and_text_field_-_material-ui](https://cloud.githubusercontent.com/assets/1088089/19824851/2e1f9d62-9d41-11e6-9c7f-df5f1f22260f.png)

Node version: `6.3.1`
Graffiti-Mongoose version: `5.3.0`

**Comment by JohnProg** [comment]
Can you show us the error that you get when you hover the line red error?

**Comment by danielmahon** [comment]
@JohnProg I will close this, I believe this was an issue on my end with `location` being a reference to another document and not actually nested itself.

**Comment by JohnProg** [comment]
Nice.
