### ISSUE TITLE
Relay release

### ISSUE THREAD

**Issue by gyzerok** [RisingStack/graffiti-mongoose#20]
@hekike have you seen todays [Relay](https://facebook.github.io/relay/) release? You may be interested in [middleware for express](https://github.com/graphql/express-graphql) provided by FB team.

**Comment by hekike** [comment]
@gyzerok yes. Exciting and `graffiti` should move forward to support it, but I didn't really have time to dig deeper.

**Comment by hardchor** [comment]
@gyzerok @hekike just noticed this when I moved https://github.com/RisingStack/graffiti-mongoose/issues/22 over. I don't think we're far off. Feel free to contribute your thoughts.
