### ISSUE TITLE
Does graffiti-mongoose works with react-apollo ?

### ISSUE THREAD

**Issue by TLevesque** [RisingStack/graffiti-mongoose#209]
Hi Everyone, does somebody know if graffiti-mongoose also works with react-apollo? Or is it limited to relay only?
Thanks, 
Thibaut

**Comment by JonathanWbn** [comment]
I am using it in my koa application and it works fine with my react-apollo frontend.

**Comment by TLevesque** [comment]
I confirm, it's handling react-apollo pretty well!
