### ISSUE TITLE
Test failing: e2e

### ISSUE THREAD

**Issue by fcmatteo** [RisingStack/graffiti-mongoose#21]
Hi, I've cloned the project and all the e2e singular query tests are failing. It's just happening to me or there's something wrong?

**Comment by hekike** [comment]
Hi! Do you have running MongoDB on your machine? It's needed for E2E tests.

**Comment by hardchor** [comment]
I'm experiencing the same. I can see it creating the test entities in mongo, but it throws this error:

```
  e2e
    get schema
      singular query
--> this is where it goes wrong { message: 'Cast to ObjectId failed for value "undefined" at path "_id"',
  locations: [ { line: 2, column: 11 } ] }
schema is:  {
          user(_id: "55daca1ed5f6e76f45f37b52") {
            _id
            name
            age
            mother {
              _id
              name
            }
            friends {
              _id
              name
            }
            objectIds
          }
        }
```


For reference, the error occurs here: https://github.com/RisingStack/graffiti-mongoose/blob/master/src/e2e.spec.js#L85

**Comment by hardchor** [comment]
Just tested a singular endpoint in my app and I'm getting the same.

```json
{
    "@risingstack/graffiti": "^1.0.2",
    "@risingstack/graffiti-mongoose": "^1.6.1",
    "mongoose": "^4.1.3",
}
```

**Comment by hardchor** [comment]
Sorry for the spam.

This could be down to this issue: https://github.com/Automattic/mongoose/issues/2646

**Comment by hekike** [comment]
@hardchor @fcmatteo do you still think this is an issue with `graffiti-mongoose`? I'm quiet surprised, we are also running the e2e tests on TravisCI. I don't see any issue with them: https://travis-ci.org/RisingStack/graffiti-mongoose/builds

**Comment by fcmatteo** [comment]
I'm sorry, I have been busy with other stuff, but yes, I have MongoDB running. In fact, the db 'graffiti-test' was created with the 'users' collection, which is empty.

**Comment by hardchor** [comment]
Had mongoose 4.1.3. 
Force-installed 4.0.6 - still broken.
Reset, reinstalled - works.

What on earth?

**Comment by fcmatteo** [comment]
I force-installed mongoose@4.0.6 and it worked.
