### ISSUE TITLE
Road towards relay compatibility

### ISSUE THREAD

**Issue by hardchor** [RisingStack/graffiti-mongoose#22]
N.B.: Moved this from https://github.com/RisingStack/graffiti/issues/7

Just putting some thoughts down of currently missing features:

### [Unique Object IDs](https://facebook.github.io/relay/docs/graphql-object-identification.html#content)

Relay wants to be able to (re-)fetch any object in the graph by a unique ID via a root query named `node`:
```
node (id: "user123") {
  id
  name
}
```

Relay methods: `fromGlobalId`/`toGlobalId`
See: https://github.com/relayjs/relay-starter-kit/blob/master/data/schema.js#L115

### [Pagination](https://facebook.github.io/relay/docs/graphql-connections.html#content)

On the query side, relay requires `first` and `after` arguments (as well as `last` and `before` for backwards pagination):
```
users (first: 10, after: "user123") {
  edges {
    cursor
    node {
      id
      name
    }
  }
  pageInfo {
    hasNextPage
  }
}
```

- `edges`: describes the collection (https://facebook.github.io/relay/graphql/connections.htm#sec-Edge-Types)
  - `cursor`: would be the unique ID discusses above
  - `node`: the box-standard field selector
- `pageInfo`: an object with meta-data about the current page (https://facebook.github.io/relay/graphql/connections.htm#sec-undefined.PageInfo)
  - `hasNextPage`
  - `hasPreviousPage`: for backwards pagination

Also see: https://facebook.github.io/relay/graphql/connections.htm

### [Mutation](https://facebook.github.io/relay/docs/graphql-mutations.html#content)

*TBC*

### Connections

I expect [graphql-relay-js](https://github.com/graphql/graphql-relay-js) to help us out with the more intricate details

I hope we can work towards relay compatibility. Please let me know if this is more appropriate for an adapter, e.g. `graffiti-mongoose`

**Comment by hardchor** [comment]
@hekike @gergelyke Are you guys still developing this? Feels like the project is already dead before it even got off the ground...

**Comment by gergelyke** [comment]
hi @hardchor,

thanks for raising them! in the past weeks sadly we did not have the time that this project would deserve - could you help us out and send a PR with these?

**Comment by hardchor** [comment]
I'm still at the crossroads which route to take:

* mongo - mongoose - graffiti or
* SQL - bookshelf - graphql-bookshelf

Before I invest any significant amount of time, how likely are you to continue this project, i.e. are you going to be using it in production apps or is it all still a bit in the air?

**Comment by gergelyke** [comment]
We definitely want to use it in production applications - with that said, I would go for finishing up one graffiti adapter implementation first, this one, so we will have a reference when working with others, like bookshelf.

What do you think?

**Comment by hardchor** [comment]
Totally agreed. Could have a bit of a catch up on Skype if you fancy.

**Comment by gergelyke** [comment]
in which timezone are you in? let's find a time which can work.

cc-ing in @hekike

**Comment by hardchor** [comment]
GMT. Added you both to https://gitter.im/hardchor/graffiti

**Comment by parkan** [comment]
Given that the cursors are specified as _opaque_, I don't see why cursors and globally unique IDs need be the same. The global id could take the format of `$collection:$_id` and cursors could be `$_id` if indexing into a collection (data structured with parent references) or maybe even numerical offsets if indexing into a subelement of child references.

**Comment by burkhardr** [comment]
@parkan They are opaque, bus as you already noted, encoded as a globally unique ID (just a simple base64 encoding)

**Comment by tothandras** [comment]
We have added the `node(ID!)` endpoint and pagination support and we are currently working on the mutation support. The new version is published on npm (`^3.0.0`). Your feedback is welcome!

**Comment by gergelyke** [comment]
I guess we can close this, right?

**Comment by hardchor** [comment]
I think we're still some way off full relay compatibility:

* `viewer` endpoint
* mutations

**Comment by tothandras** [comment]
The `viewer` endpoint and mutations have already been added. Check out the latest version!
