### ISSUE TITLE
custom resolve for a field

### ISSUE THREAD

**Issue by magalhas** [RisingStack/graffiti-mongoose#26]
Hi,

I would like to know if there's a way (or if you're envisioning one) of having a custom resolve method for a specific field. For instance, imagine I've got a field that to be populated I must engage with a third party API or another database.

Best regards.

**Comment by hekike** [comment]
hi @magalhas not yet but good idea. Could you send a pr?

**Comment by hardchor** [comment]
I guess a good place would be the graffiti models used internally? Maybe we can pick up a resolve method from mongoose models (if provided) and use them instead of the ones generated.

**Comment by tothandras** [comment]
@hardchor I agree. Eventually the graffiti models to graphql models generator should be in a different package. I made progress to decouple the implementation in this direction.

**Comment by tothandras** [comment]
I am closing this in favor of #42.
