### ISSUE TITLE
graphiQL integration

### ISSUE THREAD

**Issue by nha** [RisingStack/graffiti-mongoose#39]
I am using express and mongoose, and I suspect many do.

It would nice to have an example of a graphiQL (https://github.com/graphql/graphiql) integration.

Is the graphQL schema exposed somewhere ?

**Comment by tothandras** [comment]
Take a look at the example application, it uses graphiQL. We have a plan to serve a graphiQL instance on /graphql, but it will be part of `graffiti`. Based on our progress it should be available in the next two weeks.

**Comment by nha** [comment]
Great !

A few questions if you don't mind : 

- is it used in production somewhere ?
- is there a limit on mongoose/express versions to be used ?

**Comment by tothandras** [comment]
@nha As GraphQL itself this is an experimental project. This project is maintained and continuously evolving. I think it got to the point where you can use in production. This is not dependent on express at all, you can use any web framework to expose graphql. `graffiti-mongoose` generates the GraphQL schema from Mongoose schema, it saves you from writing it manually.

**Comment by nha** [comment]
Thanks for the reply.

I had a look at the example app (https://github.com/RisingStack/graffiti-example), but I did not see a graphiQL integration ?

My question regarding the versions is : does graffiti-mongoose needs this exact version : https://github.com/RisingStack/graffiti-mongoose/blob/master/package.json#L47
( "mongoose": "^4.1.11" ) ?
Or is it known to work with older versions (ex. I have a project using mongoose 3.6.20 right now)?

**Comment by tothandras** [comment]
@nha The GraphiQL example is [here](https://github.com/RisingStack/graffiti-mongoose/tree/master/example). It uses Mongoose promise APIs internally, most likely it won't be working. The change history might be useful: https://github.com/Automattic/mongoose/blob/master/History.md, I can't say for sure.

**Comment by tothandras** [comment]
@nha this [PR](https://github.com/RisingStack/graffiti/pull/12) includes GraphiQL option on GET when requesting `/graphql` for `graffiti`

**Comment by nha** [comment]
Cool :) I played with `graffiti` and it is nice. I still have to upgrade Mongoose to be able to use it in a real project though.

I guess it is time to close this issue.
