### ISSUE TITLE
Cursors don't work

### ISSUE THREAD

**Issue by rushidesai** [RisingStack/graffiti-mongoose#48]
In query.getList:

    selector._id = {
      $in: _id.map((id) => processId({id}))
    };

_id is not an Array. It is actually `{ $gt: ... }`

**Comment by tothandras** [comment]
Can you demonstrate the problem? I can't see the error in the code.

**Comment by tothandras** [comment]
@rushidesai Please provide more info, or I will close this.

**Comment by tothandras** [comment]
@rushidesai I am closing this for now, ping me if you have anything.
