### ISSUE TITLE
How to use graffiti-mongoose to generate the original graphql schema.js ?

### ISSUE THREAD

**Issue by sulliwane** [RisingStack/graffiti-mongoose#58]
Hi,

I have a mongoose Schema, and I'd like to have a look at the original Graphql that is generated by graffiti-mongoose. Is there some way to let graffiti-mongoose export a Schema.js file?

btw, thank you for the great work :+1:

**Comment by tothandras** [comment]
Hi @sulliwane,

you can save the user readable version of the schema to a file by using this script:
```javascript
require('babel-polyfill');
const fs = require('fs');
const path = require('path');
const graffitiMongoose = require('@risingstack/graffiti-mongoose');
const graphqlUtils = require('graphql/utilities');
const mongooseSchema = require('./schema');

const schema = graffitiMongoose.getSchema(mongooseSchema);

// Save user readable type system shorthand of schema
fs.writeFileSync(
  path.join(__dirname, './schema.graphql'),
  graphqlUtils.printSchema(schema)
);
```

**Comment by sulliwane** [comment]
@tothandras I just tried your code, and I get this error:

```
/node_modules/@risingstack/graffiti-mongoose/lib/model/model.js:121
  return mongooseModels.map(getModel).reduce(function (models, model) {
                        ^

TypeError: mongooseModels.map is not a function
    at getModels (/node_modules/@risingstack/graffiti-mongoose/lib/model/model.js:121:25)
    at Object.getSchema (/node_modules/@risingstack/graffiti-mongoose/lib/schema/schema.js:260:45)
    at Object.<anonymous> (/exportSchema.js:9:33)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```
I ```npm install babel-polyfill@6.1.19 ```, and also put ```require("babel-core/register");``` at the top of your script as my schema use ```import``` and it was not recognized.

I use node v5.

Any idea where the problem comes from? Is it related with babel 6? Thank you for you help

**Comment by tothandras** [comment]
@sulliwane 
You need to pass an array to the `getSchema` function. In this case `mongooseSchema` must be an array.

**Comment by sulliwane** [comment]
ok, it works now! awsome. Relay compatibility layer is still black magic though, so I need to take some time to make sense out of it...thanks!

**Comment by tothandras** [comment]
@sulliwane take a look at [graffiti-todo](https://github.com/RisingStack/graffiti-todo)!

**Comment by tothandras** [comment]
@sulliwane also :) https://blog.risingstack.com/graffiti-mongoose-mongodb-for-graphql/

**Comment by sulliwane** [comment]
@tothandras awesome, thanks for the notification :)

**Comment by sulliwane** [comment]
hi tothandras, When exporting the graphql.schema file using graffiti-mongoose and your script, the file is not written in plain javascript. It's graphql syntax I guess. Is there any way to export a javascript version? Also, where are the resolve functions in this file? (replaced by resolve-hooks?)

trying to understand what's going on... Thanks

**Comment by tothandras** [comment]
@sulliwane I am not sure what do you mean "javascript" version. :) You can print it out as it is if you like, but looking at the source code would make more sense.
You can find a `resolve` function on every query, mutation and field. Take a look at the source code or the [graphql-js](https://github.com/graphql/graphql-js) documentation.

**Comment by sulliwane** [comment]
this is what it looks like when exported using graffiti-mongoose:
```
input addCardInput {
  title: String
  description: String
  clientMutationId: String!
}

type addCardPayload {
  viewer: Viewer
  changedCardEdge: changedCardEdge
  clientMutationId: String!
}

type Card implements Node {
  title: String
  description: String
  _id: ID
  id: ID!
}
```

and this is what my schema looks like ("javascript"):
```
const Query = new GraphQLObjectType({
  name: 'RootQuery',
  fields: () => ({
    hello: {
      type: GraphQLString,
      resolve() {return 'world';}
    },
});

const Schema = new GraphQLSchema({
  query: Query,
  mutation: Mutation
});

export default Schema;
```
I need to read more about graphql, I may not be using it the right way...

**Comment by tothandras** [comment]
@sulliwane It's calling a lot of constructors as you can see, I am pretty sure you can't view it as it is.
