### ISSUE TITLE
Sorting by arbitrary field

### ISSUE THREAD

**Issue by marcoreat** [RisingStack/graffiti-mongoose#59]
Is there a way to specify the order of items returned by the server, e.g. `{ sort: { score: 1 } }`?

As far as I know, Relay and GraphQL have no concept of sorting. I was wondering if graffiti-mongoose allows adding the `sort` parameter to the generated queries. Or maybe there is a way to build custom queries and attach them to auto-generated ones?

**Comment by tothandras** [comment]
@marcoreat #53 There was already an issue with the same request. It seems like that you are not the only one who asks for this. :) Please read my comment there and let me know what do you think.

**Comment by marcoreat** [comment]
Thanks for the reply. I've read the linked thread, looks good to me.

In this case it's a +1 from me for the `orderBy` field and for adding this task to your feature request list.

**Comment by tothandras** [comment]
@marcoreat Okay, added. Are you using Relay? Because you can easily sort on the client side. :)

**Comment by marcoreat** [comment]
Thanks!

Yes, I'm using Relay. However AFAIK client side sorting would require fetching all the documents first and I want to avoid it (I'm dealing with large sets of data).

**Comment by tothandras** [comment]
Good point!

**Comment by hardchor** [comment]
In the meantime, you could easily do it yourself with hooks!

**Comment by marcoreat** [comment]
@hardchor I've tried it already, but didn't succeed.

I've assumed that I would be able to prepare a hook that injects the `sort` option into a mongoose call. But none of the arguments provided by `pre` or `post` seems to give access to the mongoose's mongodb query. Did I miss something? Is there another way?

**Comment by tothandras** [comment]
Currently it [sorts by _id](https://github.com/RisingStack/graffiti-mongoose/blob/master/src/query/query.js#L283), let me figure out how you can change it with hooks. I need to rewrite the logic in the source code too.

**Comment by marcoreat** [comment]
Here's a patch that adds the `orderBy` enum type. Feedback? Suggestions?
Feel free to use or modify this implementation if you like.

```diff
diff --git a/src/e2e.spec.js b/src/e2e.spec.js
index 1f70233..630ca62 100644
--- a/src/e2e.spec.js
+++ b/src/e2e.spec.js
@@ -268,6 +268,46 @@ describe('e2e', () => {
           {node: {name: 'Foo'}}
         ]);
       });
+
+      it('should return results in ascending order', async function Test() {
+        const result = await graphql(schema, `{
+          viewer {
+            users(orderBy: nameAsc) {
+              edges {
+                node {
+                  name
+                }
+              }
+            }
+          }
+        }`);
+
+        expect(result.data.viewer.users.edges).to.be.eql([
+          { node: { name: 'Bar' } },
+          { node: { name: 'Foo' } },
+          { node: { name: 'Mother' } }
+        ]);
+      });
+
+      it('should return results in descending order', async function Test() {
+        const result = await graphql(schema, `{
+          viewer {
+            users(orderBy: nameDesc) {
+              edges {
+                node {
+                  name
+                }
+              }
+            }
+          }
+        }`);
+
+        expect(result.data.viewer.users.edges).to.be.eql([
+          { node: { name: 'Mother' } },
+          { node: { name: 'Foo' } },
+          { node: { name: 'Bar' } }
+        ]);
+      });
     });
 
     describe('mutations', () => {
diff --git a/src/query/query.js b/src/query/query.js
index 1e8b766..0b5f5c5 100644
--- a/src/query/query.js
+++ b/src/query/query.js
@@ -255,7 +255,7 @@ async function connectionFromModel(graffitiModel, args, info) {
     return emptyConnection();
   }
 
-  const {before, after, first, last, id, ...selector} = args;
+  const {before, after, first, last, id, orderBy, ...selector} = args;
 
   const begin = getId(after);
   const end = getId(before);
@@ -277,10 +277,17 @@ async function connectionFromModel(graffitiModel, args, info) {
     selector._id.$lt = end;
   }
 
+  let sort = {_id: 1};
+  if (orderBy){
+    sort = {
+      [orderBy.slice(0,-3)]: orderBy.endsWith('Asc') ? 1 : -1
+    };
+  }
+
   const result = await getList(Collection, selector, {
     skip: offset,
     limit: limit,
-    sort: {_id: 1}
+    sort
   }, info);
   const count = await getCount(Collection, selector);
 
diff --git a/src/type/type.js b/src/type/type.js
index 473e202..cc8c6d9 100644
--- a/src/type/type.js
+++ b/src/type/type.js
@@ -11,6 +11,7 @@ import {
 } from 'graphql-relay';
 import {
   GraphQLString,
+  GraphQLEnumType,
   GraphQLFloat,
   GraphQLBoolean,
   GraphQLID,
@@ -77,14 +78,37 @@ function setTypeFields(type, fields) {
   type._typeConfig.fields = () => fields;
 }
 
+const orderByTypes = {};
+function getOrderByType(typeName, fields) {
+  if (!orderByTypes[typeName]){
+    orderByTypes[typeName] = new GraphQLEnumType({
+      name: typeName+"_orderBy",
+      values: reduce(fields, (values, field) => {
+        if (field.type instanceof GraphQLScalarType){
+          values[field.name+"Asc"] = { };
+          values[field.name+"Desc"] = { };
+        }
+        return values;
+      }, {})
+    });
+  }
+  return orderByTypes[typeName];
+}
+
 function getArguments(type, args = {}) {
   const fields = getTypeFields(type);
+
+  fields.orderBy = {
+    name: 'orderBy',
+    type: getOrderByType(type.name, fields)
+  };
+
   return reduce(fields, (args, field) => {
     if (field.type instanceof GraphQLNonNull && field.name !== 'id') {
       field.type = field.type.ofType;
     }
 
-    if (field.type instanceof GraphQLScalarType) {
+    if (field.type instanceof GraphQLScalarType || field.type instanceof GraphQLEnumType) {
       args[field.name] = field;
     }
 
```

**Comment by tothandras** [comment]
@marcoreat Let me try it out ;)

**Comment by tothandras** [comment]
Thank you @marcoreat! I have used your code with a few changes: #61. I prefer to use upper case for enum types.

**Comment by marcoreat** [comment]
I like your changes, :+1: .

**Comment by burkhardr** [comment]
What about `name asc` or `name ASC'? Seen it used that way in several other tools.

**Comment by tothandras** [comment]
#61 is merged and released under `4.3.0`.

**Comment by marcoreat** [comment]
Thanks! :tada:

**Comment by pbrain19** [comment]
please add to readme.

**Comment by unirey** [comment]
@tothandras Im not using Graffiti but I really, really need the sorting support with Relay cursors for all fields, including non-unique or non-indexed fields. 

Could you please explain briefly the main idea behind #61 so that I could implement it with Mongoose?

**Comment by tothandras** [comment]
@unirey sure. The `orderBy` parameter has a type of `GraphQLEnumType`. For each field in your model you need to make two possible [`value`](https://github.com/RisingStack/graffiti-mongoose/pull/61/files#diff-87327454bbf7054756bdd421367ddfd4R86) for this enum. I've named it `field.name.toUpperCase() + '_DESC'` for descending order and `field.name.toUpperCase() + '_ASC'` for ascending order. In Mongoose when using the [`sort`](https://github.com/RisingStack/graffiti-mongoose/pull/61/files#diff-986913820b67d062c1473afc9b939a89R283) option it waits for an object like `{ name: -1 }`. `-1` stands for descending, `+1` for ascending order. You need to set [the enum values] (https://github.com/RisingStack/graffiti-mongoose/pull/61/files#diff-87327454bbf7054756bdd421367ddfd4R89) according to this. In you query it will look something like this:
```
{
          viewer {
            users(orderBy: NAME_DESC) {
              edges {
                node {
                  name
                }
              }
            }
          }
       }
```
