### ISSUE TITLE
Return better mongoose errors 

### ISSUE THREAD

**Issue by voronianski** [RisingStack/graffiti-mongoose#66]
For example I have model with required field:

```javascript
import mongoose from 'mongoose';

const UserSchema = new mongoose.Schema({
    email: {
        type: String,
        unique: true,
        trim: true,
        required: 'Email is required'
    },

    createdAt: {
        type: Date,
        default: Date.now
    }
});

const User = mongoose.model('User', UserSchema);

export default User;
```

but when I send mutation to server like `{"mutation { addUser(input: {clientMutationId: "1"}) { clientMutationId } }"}` I receive not well enough descriptive error:

```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "User validation failed"
}
```

**Comment by tothandras** [comment]
Hi @voronianski! The error messages are not specified by `graffiti-mongoose`. An error message could come either from Mongoose or from GraphQL itself (caught exception for example).

**Comment by voronianski** [comment]
@tothandras it's mongoose error but it should be overwritten with `'Email is required'` message specified in mongoose schema, what version of mongoose do you use?

**Comment by tothandras** [comment]
@voronianski `4.2.8`

**Comment by tothandras** [comment]
@voronianski anything else? Can we do something to improve the error messages?

**Comment by voronianski** [comment]
@tothandras sorry I don't have time to investigate it now, will close it for now.

**Comment by danielmahon** [comment]
Was there ever any update to this?
