### ISSUE TITLE
Mutation resolve hooks question

### ISSUE THREAD

**Issue by mincedmit** [RisingStack/graffiti-mongoose#67]
Hi!

You mentioned in the docs:

>You can add hooks to type fields and query fields (singular & plural queries, mutations) too. By passing arguments to the next function, you can modify the parameters of the next hook or the return value of the resolve function."

Curious what is meant by "passing arguments to the next function..." -- how does one make use of this functionality?

One example of what I'm trying to do is get access to the original mutation context object (the third argument to the pre hook) in the post hook.  The reason for that is I want to introspect on the mutation that occurred to determine any side effects, but I want to do that AFTER the mutation is complete not before (where I have access to this information)  Is there a simple way to do this via the next callback?  Can I effectively pass that "through" to the post hook?

**Comment by tothandras** [comment]
Hi @mincedmit!
Take a look at the PR #68. You will be able to access the context in post hooks too. If you want to add something to the context in a pre hook and use it in a post hook, you can do that now.

**Comment by tothandras** [comment]
@mincedmit Please close the issue if version `4.3.1` fixed your issue.
