### ISSUE TITLE
Two fields with the same name across different schemas result in conflicting connection type

### ISSUE THREAD

**Issue by rushidesai** [RisingStack/graffiti-mongoose#72]
var PersonSchema = new Schema({
      friends: {
        type: [mongoose.Schema.Types.ObjectId],
        ref: 'Person',
      }
    });

    var EmployeeSchema = new Schema({
      friends: {
        type: [mongoose.Schema.Types.ObjectId],
        ref: 'Employee',
      }
    });

This results in generating `friendsConnection` twice.

**Comment by tothandras** [comment]
@rushidesai Is it causing an error on type creation, right? What names should you prefer in this case? `PersonFriendsConnection` & `EmployeeFriendsConnection`?

**Comment by rushidesai** [comment]
Those names are unique and hence would work.

**Comment by tothandras** [comment]
@rushidesai #74
