### ISSUE TITLE
[possible bug] updating array of strings

### ISSUE THREAD

**Issue by dzannotti** [RisingStack/graffiti-mongoose#75]
having described in my model `images: [String]` when i attempt to save
```
images: [
  "fc6092ab09574edd9cb82c665f97fb0b"
  "c01a8ab7196e45c6981cb58f58152db6"
  "3bcd62558a8a444ea9f1996efda062de"
  "a23530eb3694408f8e8ef3a81fe3ceed"
  "77dd890281ea4cd8b2cb4487c433dcdf"
]
```

in the database seems to save 
```
"images": [
        "e\u007f{}=\u001b",
        "wM\\o\u001f\u001fgMyYVz",
        "3bcd62558a8a444ea9f1996efda062de",
        "a23530eb3694408f8e8ef3a81fe3ceed",
        "77dd890281ea4cd8b2cb4487c433dcdf"
    ]
```

This doesn't seems to be consistently reproduceable but seems to happen only when the value of the string contains hashes (perhaps they get confused at times with `ObjectId`?)

**Comment by tothandras** [comment]
Yes, you are right! There is a fix hidden in [this](https://github.com/RisingStack/graffiti-mongoose/commit/6aa58202cd0b8c882a7ecf06a6588c23a21e4817) commit, but it hasn't been released yet. I'll do a release soon, it will most likely fix your problem.

**Comment by dzannotti** [comment]
Sadly I'm already using that version and doesn't seem to fix the issue

**Comment by tothandras** [comment]
hmm... strange :/ Let me take a look at it in a few hours (just got home from the SW premier, it's already 4am :)) It would be nice if you could test it too, so you might find where the error comes from.

**Comment by tothandras** [comment]
Okay, I think it's fixed now. Try out version `5.0.1`!

**Comment by dzannotti** [comment]
@tothandras oh wow, i wasn't expecting such a quick fix! Was going to write some tests for it and PR tonight with a fix, but you got was waaay ahead of me. Will test it out, that's great, i do wonder if a safer way to figure out if the id is of mongo or global relay is to verify if it ends with `=` as originally was checking along other things, graphql-relay uses base64 encoding to it'll always end with `=` while to the best of my knowledge no mongoid will do that

**Comment by tothandras** [comment]
Yes, you are right! I was thinking about that before, but as far as I know
`=` at the end indicates duplicated characters or something. I wasn't brave
enough to use this, but at the same time I couldn't find an ID without it.
:)

**Comment by dzannotti** [comment]
To the best of my knowledge `=` is used as padding to indicate that the last character encoded is 8 or 16 bits, so in theory not every base64 string would end with a `=` however i never came across one that didn't have it. Not had the chance to try the fix yet however after reporting this issue, it seem to have appear randomly on other string fields (not necesarly arrays). WIll upgrade and investigate as soon as i can

**Comment by tothandras** [comment]
@dzannotti You are most certainly right, I don't trust my memories. :) Update me if you tried it!

**Comment by dzannotti** [comment]
yep confirmed working in 5.0.1, thank you for this!

**Comment by tothandras** [comment]
@dzannotti Thanks for the bug report!
