### ISSUE TITLE
orderBy argument has no effect

### ISSUE THREAD

**Issue by jkempff** [RisingStack/graffiti-mongoose#77]
The two `orderBy` tests in `e2e.spec.js` dont fail, if you switch `NAME_DESC` to `NAME_ASC` (and vice versa).

I noticed, that the actual `Collection.find` call in `query.js` gets called with

```
{
  sort: 'NAME_DESC'
}
```
instead of 
```
{
  sort: { name: -1 }
}
```

It seems like the order keys somehow don't get resolved into the corresponding mongoose option.
If you can give me a bump in the right direction, I'd be happy to fix this.

**Comment by tothandras** [comment]
schema.js and query.js should contain everything you need. I will look into
it too.
