### ISSUE TITLE
Cannot query field "fieldName" on "addSomeCollectionNamePayload"

### ISSUE THREAD

**Issue by cheunghy** [RisingStack/graffiti-mongoose#82]
Hi, Thanks for this fantastic module.

However, when I do according to the example, I get an error. And I don't know why it errors.

The schema
``` js
  const languageSchema = mongoose.Schema({
    name: {
      type: String,
      validate: {
        validator: function(v) {
          return _.isString(v) && v.length;
        },
        message: 'Language name should be present.'
      }
    }
  });
```

The query
``` graphql
mutation addLanguageJapanese {
    addLanguage(input: {clientMutationId: "anyString", name: "Japanese"}) {
        name, id
    }
}
```
The response
``` json
{
  "errors": [
    {
      "message": "Cannot query field \"name\" on \"addLanguagePayload\"."
    },
    {
      "message": "Cannot query field \"id\" on \"addLanguagePayload\"."
    }
  ]
}
```

**Comment by tothandras** [comment]
Hi @cheunghy, 
Use the Documentation Explorer (`< Docs` on the right top) of GraphiQL to explore the generated schema if you are unsure about it. In your case the mutation should look like this:
```
mutation addLanguageJapanese {
  addLanguage(input: {clientMutationId: "anyString", name: "Japanese"}) {
      changedLanguageEdge {
        node {
          name
          id
        }
      }
  }
}
```

**Comment by tothandras** [comment]
Thanks for the notice, the examples are out of date. I will update them.

**Comment by cheunghy** [comment]
Seems the example is correct, I use it wrongly.

IMHO, it's better to explain in the example why we need "changed...Edge" field, to let novices understand.

**Comment by cheunghy** [comment]
Thanks.
But I still don't understand why it needs to wrap the value in changed...Edge and node.

```
      changed...Edge {
        node {

        }
      }
```

**Comment by tothandras** [comment]
@cheunghy It's necessary because this is how Relay requires the data. See [graffiti-todo](https://github.com/RisingStack/graffiti-todo).
