### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined on npm run coverage

### ISSUE THREAD

**Issue by sibeliusseraphini** [RisingStack/graffiti-mongoose#85]
I'm receiving this error on ```npm run coverage```

```
ReferenceError: regeneratorRuntime is not defined
    at /Users/sibelius/Dev/rturk/graffiti-mongoose/src/query/query.js:9:19199
```

**Comment by tothandras** [comment]
Babel polyfill is a peer dependency of this project: add `require('babel-polyfill')` to your application entry point.

**Comment by tothandras** [comment]
`"coverage": "NODE_ENV=test babel-istanbul cover _mocha -- --require babel-polyfill 'src/**/*.spec.js'"` does work. ;)

**Comment by sibeliusseraphini** [comment]
it works with the comment above
