### ISSUE TITLE
Use mongoose-compatible plurals for model names

### ISSUE THREAD

**Issue by azmum** [RisingStack/graffiti-mongoose#91]
Mongoose uses a set of rules to get the plural form of a model name to create the collection.
This is problematic as graffiti-mongoose only adds an "s" to make plurals, and it can be ugly and inconsistent.

I suggest to use [the same rules](https://github.com/Automattic/mongoose/blob/master/lib/utils.js) as Mongoose.

**Comment by tothandras** [comment]
@azmum take a look at #91.
