### ISSUE TITLE
Order By is not working

### ISSUE THREAD

**Issue by robmanh** [RisingStack/graffiti-mongoose#92]
Hi there,
i'm working now a few days with graffiti-mongoose. i like this library very much. But some important issues are missing. Special for modifying queries and mutations. Also for security reasons. 
But for this topics are some open issues existing. good job so far :+1: 

Now i found a bug without an open task for. If i try to sort by  `users(orderBy:NAME_ASC) ` it return an empty array. The generated mongoose code `users.find({ orderBy: { name: 1 } })` will not work.
If i use the normal mongoose request `users.find({}).sort({ name: 1 } )`  the expected array return.

**Comment by tothandras** [comment]
Thank you, fixed!
