### ISSUE TITLE
The 'count' value in the connection (relay)

### ISSUE THREAD

**Issue by vangavroche** [RisingStack/graffiti-mongoose#98]
Should this 'count' be the total number of the connection (which defines by the filter args, excluding the pagination args)?

The "first / after" are pagination args, but in the Query getCount https://github.com/RisingStack/graffiti-mongoose/blob/master/src/query/query.js#L18  the selector used to count the data contains the "gt", which is used for "after"

I think this is an issue. How do you think?

**Comment by tothandras** [comment]
It should be the total count, which helps you with page indication on your UI.
